version: '3.7'

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - gem_bundles:/usr/local/bundle
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: todo_app_development
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
  gem_bundles:
