defaults: &defaults
  uri: <%= ENV['MONGODB_URI'] %>
  options:
    ssl: false

development:
  <<: *defaults

test:
  <<: *defaults

# set these environment variables on your prod server
production:
  <<: *defaults
